"""Plain-language definitions of every term used in the app.

Each entry: (key, display name, category, one-line meaning, longer explanation, formula (optional), aliases (labels used in the app)).
Keep the one-line meaning under ~90 characters: it is shown inside result cards.
"""

# fmt: off
ENTRIES = [
# =====================================================================  SENSOR BASICS
("measurand", "Measurand", "Sensor basics", "The physical quantity you want to measure.",
 "The measurand is the input of the sensor, for example acceleration (g), pressure (kPa), force (N), strain (µε) or the refractive index of a liquid (RIU).",
 "", ["input", "measurand range"]),
("transducer", "Transducer", "Sensor basics", "The part that converts one form of energy into another.",
 "A sensor usually contains a transducer that converts the measurand (mechanical, optical, thermal ...) into an electrical or optical signal you can read. "
 "This app groups transducers as mechanical (mass-spring-damper), electrical (piezoresistive, piezoelectric) and optical (WGM, FBG, Fabry-Perot, SPR).",
 "", ["transduction principle", "sensor type"]),
("output", "Output signal", "Sensor basics", "What the sensor delivers: a voltage, a wavelength shift, an angle ...",
 "The output is the number you actually read. Calibration turns it back into the measurand.", "", ["y"]),
("sensitivity", "Sensitivity (S)", "Sensor basics", "How much the output changes per unit change of the measurand.",
 "Sensitivity is the slope of the calibration curve. A sensor with 300 mV/g changes its output by 300 mV when the acceleration changes by 1 g. "
 "A higher sensitivity makes small changes easier to see above the noise, but it does not by itself make a sensor better: what counts is sensitivity compared with noise (see detection limit).",
 "S = Δy / Δx = dy/dx", ["sensitivity (model)", "sensitivity s (measured)", "sensitivity s", "bulk sensitivity s", "mechanical sensitivity",
                          "linear electrical sensitivity", "angular sensitivity", "strain sensitivity", "temperature sensitivity", "charge sensitivity",
                          "flat-band voltage sensitivity", "normalised sensitivity"]),
("full_scale", "Full-scale output (span)", "Sensor basics", "Output change over the whole measurement range.",
 "Full-scale output (FS) is the difference between the output at the top and at the bottom of the measurand range. Many errors are quoted as a percentage of it (% FS).",
 "y_FS = y(x_max) − y(x_min)", ["full-scale output", "span"]),
("range", "Measurement range", "Sensor basics", "The lowest and highest values the sensor is used for.",
 "You choose it in the sidebar. Outside the range the sensor may saturate, become very nonlinear or be damaged.", "", ["measurand range"]),
("offset", "Offset (zero output)", "Sensor basics", "The output when the measurand is zero.",
 "An ideal sensor gives 0 at zero input. Real sensors have an offset (for example from resistor mismatch in a bridge). It can be removed by calibration, but it changes with temperature (offset drift).",
 "", ["offset (y at x = 0)", "offset at 0 kpa"]),
("calibration", "Calibration", "Sensor basics", "Measuring the sensor against known inputs to find its equation.",
 "During calibration you apply known values of the measurand, record the output several times, and fit a curve. The curve then lets you convert any later output into a measurement.", "", []),
("calibration_curve", "Calibration curve", "Sensor basics", "The graph of sensor output against the known input.",
 "Each point is the mean of repeated readings at one level; the bars show the standard deviation. The line is the least-squares fit.", "", ["calibration curve and equation"]),
("calibration_equation", "Calibration equation", "Sensor basics", "The formula of the fitted line, output = a₁·x + a₀.",
 "For a straight line, a₁ is the sensitivity and a₀ the offset. Higher-order fits add x² and x³ terms to follow nonlinear sensors.", "y = a₀ + a₁x + a₂x² + …", []),
("inverse_calibration", "Inverse calibration", "Sensor basics", "Turning a reading back into a measurement.",
 "After calibration you measure the output y and solve the equation for x. For a straight line: x = (y − a₀)/a₁.", "x̂ = (y − a₀)/a₁", ["reading a measurement"]),
("accuracy", "Accuracy", "Sensor basics", "How close the result is to the true value.",
 "Accuracy includes systematic errors (offset, gain error, nonlinearity, drift) and random errors (noise). In the app it is reported as the RMS error after calibration.", "", ["accuracy after calibration (rms)"]),
("precision", "Precision / repeatability", "Sensor basics", "How close repeated readings are to each other.",
 "Repeatability is the scatter of repeated readings of the same input under the same conditions. It is expressed here as ±2 standard deviations as a percentage of full scale.",
 "ε_R = 2·max(s) / y_FS", ["repeatability", "repeatability (±2σ)"]),
("resolution", "Resolution", "Sensor basics", "The smallest change of the measurand you can tell apart.",
 "Here it is the noise (one standard deviation) divided by the sensitivity: the input change that produces an output change equal to the noise.", "δx = σ / S", ["resolution (1σ)"]),
("noise", "Noise", "Sensor basics", "Random fluctuation of the output that limits small measurements.",
 "Noise comes from thermal motion (Johnson and Brownian noise), electronics, lasers, and so on. It is measured as the standard deviation of repeated readings of a constant input.", "", ["noise, 1 sd", "noise (1 sd)"]),
("snr", "Signal-to-noise ratio (SNR)", "Sensor basics", "Size of the signal compared with the noise, often in dB.",
 "SNR in decibels is 20·log10(signal/noise). A high SNR means a clean measurement. For optical resonance sensors it is the depth of the resonance dip divided by the noise.",
 "SNR = 20 log₁₀(y_FS / σ)", ["signal-to-noise at full scale"]),
("dynamic_range", "Dynamic range", "Sensor basics", "Ratio of the largest to the smallest usable signal, in dB.",
 "It compares the full-scale output with the smallest signal that can be detected (three standard deviations).", "DR = 20 log₁₀(y_FS / 3σ)", ["dynamic range"]),
("lod", "Limit of detection (LOD)", "Sensor basics", "The smallest amount of the measurand you can reliably detect.",
 "The LOD is the input whose output equals three times the noise. Below it the signal cannot be told apart from noise. Two variants are shown: 3σ₀/S (IUPAC, blank noise) and 3.3·s_res/S (ICH, residual noise of the fit).",
 "LOD = 3σ / S", ["detection limit 3σ/s", "detection limit 3σ/s ", "lod (3σ₀/s)", "detection limit", "limit of detection (3σ₀/s)", "limit of detection (3.3 s_res/s)", "detection limit 3 sigma / s"]),
("loq", "Limit of quantification (LOQ)", "Sensor basics", "The smallest amount you can measure with acceptable precision.",
 "Set at ten times the noise divided by the sensitivity. Between LOD and LOQ you know something is there, but not exactly how much.", "LOQ = 10σ / S", ["limit of quantification (10σ₀/s)"]),
("nonlinearity", "Nonlinearity", "Sensor basics", "How far the sensor curve departs from a straight line.",
 "Measured as the largest deviation of the level means from the best-fit line, as a percentage of full scale. A pattern in the residual plot reveals it.",
 "ε_NL = max|ȳᵢ − ŷᵢ| / y_FS", ["nonlinearity", "linearity"]),
("hysteresis", "Hysteresis", "Sensor basics", "Different output when approaching a value from above or below.",
 "Measured by sweeping the input up and then down. The largest difference between the two curves, as a percentage of full scale, is the hysteresis. It needs the sweep direction 'up and down'.",
 "ε_H = max|ȳ↑ − ȳ↓| / y_FS", []),
("drift", "Drift", "Sensor basics", "Slow change of the output that is not caused by the measurand.",
 "Most often caused by temperature. Drift shows up as a change of offset (zero shift) and of sensitivity. The ML page can learn to correct it.", "", []),
("temperature_coefficient", "Temperature coefficient", "Sensor basics", "Relative change of a property per kelvin.",
 "For example −60 ppm/K for the stiffness of silicon means the spring becomes 0.006 % softer for every kelvin of temperature increase.", "", ["tck", "temperature coefficient of sensitivity"]),
("cross_sensitivity", "Cross-sensitivity", "Sensor basics", "Unwanted response to something other than the measurand.",
 "A fibre Bragg grating responds to temperature as well as strain: 1 K looks like about 11 µε. The 'cross-sensitivity' value tells you how large this error is.", "", ["cross-sensitivity", "temperature sensitivity"]),
("bandwidth", "Bandwidth", "Sensor basics", "The range of frequencies the sensor follows.",
 "For a dynamic sensor the −3 dB bandwidth is the frequency where the response has dropped to 71 % of its low-frequency value. In the noise formulas 'measurement bandwidth' B is the range of frequencies the read-out accepts: noise power grows with B.",
 "", ["bandwidth (-3 db)", "bandwidth f-3db", "measurement bandwidth", "usable bandwidth (~f1/3)"]),
("riu", "RIU (refractive-index unit)", "Sensor basics", "The unit of refractive index change.",
 "1 RIU is a change of the refractive index by 1.0. Water is 1.33, so realistic changes are 10⁻⁷ to 10⁻² RIU. 'nm/RIU' says how many nanometres the resonance moves per RIU.", "", []),
("full_scale_pct", "% FS (percent of full scale)", "Sensor basics", "An error expressed relative to the whole output range.",
 "A 0.5 % FS error on a 0–100 kPa sensor means ±0.5 kPa anywhere in the range.", "", ["% fs"]),

# =====================================================================  CALIBRATION STATISTICS
("mean", "Mean (average)", "Calibration statistics", "The average of repeated readings at one level.",
 "The 'mean ± SD' points in the calibration curve are the mean of the repeated readings at that input.", "ȳ = Σyⱼ / n", []),
("sd", "Standard deviation (SD)", "Calibration statistics", "How much repeated readings scatter around their mean.",
 "About 68 % of readings fall within ±1 SD of the mean if the noise is Gaussian. A small SD means good repeatability. It is the number the detection limit is built on.",
 "s = √[Σ(yⱼ − ȳ)² / (n−1)]", ["standard deviation", "sd", "standard deviation at each level"]),
("pooled_sd", "Pooled standard deviation", "Calibration statistics", "One SD that summarises all calibration levels.",
 "The root-mean-square of the SDs at each level. It is the single 'noise' number used for resolution and detection limit.", "s_pooled = √[(1/N)Σsᵢ²]", ["pooled sd σ", "pooled standard deviation"]),
("sem", "Standard error of the mean (SEM)", "Calibration statistics", "Uncertainty of the mean, smaller than SD.",
 "The mean of n readings is more certain than one reading: SEM = SD/√n. Taking more repeats makes the mean more precise, but the SD stays the same.", "SEM = s / √n", ["sem"]),
("ci95", "95 % confidence interval", "Calibration statistics", "Range that contains the true mean with 95 % probability.",
 "Calculated from the SEM and the Student t-value. If two intervals do not overlap, the means are probably really different.", "CI₉₅ = t·SEM", ["95 % ci ±", "ci95"]),
("standard_error", "Standard error of a coefficient", "Calibration statistics", "Uncertainty of a fitted number such as the slope.",
 "The '± 0.74 (1 SE)' next to the sensitivity says the slope is known to about ±0.74 mV/g. More levels and repeats make it smaller.", "", ["standard error", "standard error of s"]),
("least_squares", "Least-squares fit", "Calibration statistics", "Finding the curve that minimises the squared errors.",
 "The calibration line is placed so that the sum of the squared vertical distances to the readings is as small as possible.", "", ["regression"]),
("wls", "Weighted least squares", "Calibration statistics", "A fit that trusts low-noise levels more.",
 "Each level gets a weight 1/SD². It is useful when the noise grows with the signal.", "", []),
("poly_order", "Polynomial order", "Calibration statistics", "How many bends the calibration curve may have.",
 "Order 1 is a straight line, 2 a parabola, 3 a cubic. Use a higher order only if the residuals of the straight line show a clear pattern.", "", ["calibration polynomial order"]),
("residual", "Residual", "Calibration statistics", "Difference between a measured mean and the fitted curve.",
 "Random residuals mean the model fits well. A systematic pattern (for example an 'S' shape) means the sensor is nonlinear and a higher order is needed.", "", ["residuals (a pattern = nonlinearity)", "residuals"]),
("r2", "R² (coefficient of determination)", "Calibration statistics", "Fraction of the variation explained by the fit; 1 is perfect.",
 "R² close to 1 does not prove the sensor is linear: a slightly curved sensor can still give 0.999. Always look at the residuals as well.", "R² = 1 − Σ(y−ŷ)² / Σ(y−ȳ)²", ["r²", "r² / adjusted r²"]),
("rmse", "RMSE (root-mean-square error)", "Calibration statistics", "Typical size of the error, in the units of the output.",
 "The square root of the mean squared difference between data and fit (or between prediction and truth).", "RMSE = √[Σ(y−ŷ)² / M]", ["rmse"]),
("rsd", "RSD (relative standard deviation)", "Calibration statistics", "SD as a percentage of the mean.", "RSD = 100·SD/mean.", "", ["rsd %"]),
("model_vs_measured", "Model vs measured sensitivity", "Calibration statistics", "How far the fitted sensitivity is from the theory value.",
 "A small difference means the virtual experiment reproduces the physics. Reference uncertainty, temperature jitter and nonlinearity widen the gap.", "", ["model vs measured s"]),
("reference_uncertainty", "Reference uncertainty", "Calibration statistics", "Error of the calibrator or standard.",
 "No calibration is better than the instrument that produces the known input. It is given as a percentage of full scale.", "", ["reference uncertainty [% fs]"]),
("temp_stability", "Temperature stability", "Calibration statistics", "How steady the chamber temperature is during calibration.",
 "Sensors with a large temperature coefficient turn temperature fluctuations into extra noise.", "", ["temperature stability σ_t [k]"]),
("noise_multiplier", "Noise multiplier", "Calibration statistics", "A knob that scales the sensor noise up.",
 "Use it to make the scatter visible in the plots or to see how a noisier read-out changes the detection limit.", "", []),
("seed", "Random seed", "Calibration statistics", "A number that makes the random noise repeatable.",
 "The same seed gives exactly the same 'random' readings every time. Change it to see a new noise sample.", "", []),
("levels_repeats", "Calibration levels and repeats", "Calibration statistics", "How many inputs, and how many readings at each.",
 "More levels reveal nonlinearity; more repeats give a better estimate of the standard deviation and a smaller standard error of the sensitivity.", "", []),
("lhs", "Latin-hypercube sampling", "Calibration statistics", "A way to spread random designs evenly over the parameter ranges.",
 "Compared with pure random sampling it avoids clumps and gaps, so fewer designs are needed to cover the space.", "", []),

# =====================================================================  MECHANICAL
("msd", "Mass-spring-damper", "Mechanical sensor", "A proof mass on a spring with damping; the basis of accelerometers.",
 "When the housing accelerates, the mass lags behind and the spring stretches. The displacement is x = m·a/k and is read out electrically (here capacitively).", "m·ẍ + c·ẋ + k·x = m·a", []),
("proof_mass", "Proof mass (m)", "Mechanical sensor", "The moving mass that reacts to acceleration.",
 "A heavier mass gives a larger displacement per g (higher sensitivity) and less thermal (Brownian) noise, but a lower resonance frequency.", "", ["proof mass m"]),
("stiffness", "Spring stiffness (k)", "Mechanical sensor", "How hard it is to stretch the spring.",
 "A softer spring (small k) gives more displacement and higher sensitivity but a lower resonance frequency: the sensitivity-bandwidth trade-off.", "", ["spring stiffness k"]),
("f0", "Natural frequency (f₀)", "Mechanical sensor", "The frequency at which the mass-spring system likes to vibrate.",
 "Above it the sensor no longer follows the input. Sensitivity times f₀² is constant, so raising one lowers the other.", "f₀ = √(k/m) / 2π", ["natural frequency f0"]),
("damping_ratio", "Damping ratio (ζ)", "Mechanical sensor", "How strongly vibrations die out.",
 "ζ = 0.7 gives the flattest response and no ringing. Small ζ rings for a long time; large ζ is sluggish.", "ζ = c / (2√(km))", ["damping ratio zeta", "damping coefficient c"]),
("q_mech", "Quality factor (Q)", "Mechanical sensor", "How sharp the resonance is; Q = 1/(2ζ).",
 "A high Q means little damping: the sensor rings, and Brownian noise falls. The same idea is used for optical resonators, where Q is much larger (10⁶).", "Q = 1/(2ζ)", ["quality factor q"]),
("bw3db", "−3 dB bandwidth", "Mechanical sensor", "Frequency where the response has fallen to 71 %.",
 "It is the usable frequency range of the accelerometer. It depends on f₀ and the damping ratio.", "f₋₃dB = f₀√u, u = (1−2ζ²)+√[(1−2ζ²)²+1]", []),
("electrode_gap", "Electrode gap (d₀)", "Mechanical sensor", "Distance between the capacitor plates at rest.",
 "A smaller gap gives a larger relative change of capacitance (higher sensitivity) but risks pull-in and squeeze-film damping. The displacement should stay below about 30 % of the gap.", "", ["electrode gap d0", "max displacement / gap"]),
("capacitive", "Capacitive read-out", "Mechanical sensor", "Measuring displacement through a change of capacitance.",
 "The moving mass is one plate of a capacitor. Its displacement changes the capacitance, and an amplifier turns this into a voltage.", "V_out = G·V_b·x/d₀", []),
("bias_voltage", "Bias voltage (V_b)", "Mechanical sensor", "The voltage applied to the capacitor.", "Output voltage grows in proportion to it.", "", ["bias voltage v_b"]),
("gain", "Read-out gain (G)", "Mechanical sensor", "How much the electronics amplify the signal.", "Multiplies the sensitivity and also the electronic noise.", "", ["readout gain g"]),
("brownian", "Brownian (thermo-mechanical) noise", "Mechanical sensor", "Noise from the random thermal motion of the proof mass.",
 "Even with perfect electronics the mass jiggles because of heat. It falls with a larger mass and a higher Q.", "a_n = √(4k_B T ω₀ / (m Q))", ["brownian noise floor", "electronic noise floor"]),
("noise_density", "Noise density (per √Hz)", "Mechanical sensor", "Noise per square-root of bandwidth.",
 "Amplifier noise is quoted as, for example, 12 µV/√Hz. Multiply by √B (bandwidth) to get the noise voltage: halving the bandwidth lowers noise by 30 %.", "", ["amplifier input noise e_n", "amplifier / adc noise", "amplifier voltage noise e_n", "amplifier voltage noise"]),
("duffing", "Spring nonlinearity (β)", "Mechanical sensor", "The spring gets stiffer when stretched far.",
 "A cubic term in the spring force bends the calibration curve. It is the origin of the S-shaped residuals you see for large accelerations.", "k·x + k₃x³ = m·a", ["spring cubic nonlinearity beta"]),
("pullin", "Pull-in", "Mechanical sensor", "Collapse of the moving plate onto the electrode.",
 "When the displacement is more than about a third of the gap, electrostatic forces overwhelm the spring. The app warns before this happens.", "", []),
("tck", "Temperature coefficient of stiffness (TCK)", "Mechanical sensor", "How the spring stiffness changes with temperature.",
 "Silicon becomes softer when hot (about −60 ppm/K), so the sensitivity drifts with temperature.", "", ["temp. coeff. of stiffness"]),

# =====================================================================  PIEZORESISTIVE
("piezoresistive", "Piezoresistive effect", "Piezoresistive sensor", "Resistance changes when the material is strained.",
 "In silicon the effect is about 60 times stronger than in a metal foil because strain changes the way electrons move (the band structure), not just the geometry.", "ΔR/R = GF·ε", []),
("gauge_factor", "Gauge factor (GF)", "Piezoresistive sensor", "Relative resistance change per unit strain.",
 "Metal foil: about 2. p-type silicon: 100–150. A higher GF gives a higher sensitivity.", "GF = 1 + 2ν + π_L·E", ["gauge factor gf"]),
("strain", "Strain (ε)", "Piezoresistive sensor", "Relative stretch of the material.",
 "Strain is change of length divided by length. 1 µε (microstrain) is a stretch of one part in a million.", "ε = ΔL / L", ["strain at full scale", "strain"]),
("stress", "Stress (σ)", "Piezoresistive sensor", "Force per unit area inside the material.",
 "The peak stress of the diaphragm must stay well below the fracture strength of silicon (a few hundred MPa in practice); the app warns about this.", "", ["max stress at full scale"]),
("diaphragm", "Diaphragm", "Piezoresistive sensor", "A thin plate that bends under pressure.",
 "In the piezoresistive sensor the resistors sit near the clamped edge, where the strain is largest. A thin, wide diaphragm gives high sensitivity but low resonance frequency and a risk of breaking.", "S ∝ (a/h)²", ["diaphragm side length a", "diaphragm thickness h"]),
("youngs_modulus", "Young's modulus (E)", "Piezoresistive sensor", "Stiffness of the material.",
 "Silicon: about 130–190 GPa depending on direction. A stiffer material bends less for the same pressure.", "", ["young's modulus e"]),
("poisson", "Poisson ratio (ν)", "Piezoresistive sensor", "Sideways shrinkage when a material is stretched.",
 "Around 0.28 for silicon. It enters the plate formulas and the gauge factor.", "", ["poisson ratio nu"]),
("wheatstone", "Wheatstone bridge", "Piezoresistive sensor", "Four resistors that turn a tiny resistance change into a voltage.",
 "Two arms increase and two decrease with strain, so the output is large and the temperature effects largely cancel. The output is zero when the bridge is balanced.", "V_out = V_s·ΔR/R (full bridge)", ["bridge configuration"]),
("bridge_types", "Full, half and quarter bridge", "Piezoresistive sensor", "How many of the four resistors are active.",
 "A full bridge (4 active arms) gives the highest signal and best temperature compensation; a quarter bridge (1 arm) gives about a quarter of the signal and is nonlinear.", "", []),
("supply_voltage", "Bridge supply voltage (V_s)", "Piezoresistive sensor", "The voltage that powers the bridge.",
 "Output is proportional to it, so doubling V_s doubles the sensitivity, but it also heats the resistors (self-heating).", "", ["bridge supply voltage vs"]),
("bridge_resistance", "Bridge resistance (R₀)", "Piezoresistive sensor", "Resistance of each bridge arm.",
 "Sets the Johnson noise and the current drawn. Higher R₀ means more thermal noise but less power.", "", ["bridge resistance r0"]),
("doping", "Doping concentration (N)", "Piezoresistive sensor", "How many impurity atoms the silicon contains.",
 "Light doping gives the highest gauge factor but a large temperature dependence. Heavy doping is more stable but less sensitive: the classic sensitivity versus thermal stability trade-off.", "", ["doping concentration n"]),
("piezo_factor", "Piezoresistance factor P(N)", "Piezoresistive sensor", "How much the piezoresistive coefficient is reduced by doping.",
 "1 for light doping, falling to about 0.3 for very heavy doping (Kanda trend).", "", ["piezoresistance factor p(n)"]),
("tcgf", "TCGF", "Piezoresistive sensor", "Temperature coefficient of the gauge factor.",
 "In p-type silicon the gauge factor falls by about 0.1 to 0.3 % per kelvin, so the sensitivity drops when it gets hot.", "", ["tcgf"]),
("tcr", "TCR", "Piezoresistive sensor", "Temperature coefficient of resistance.",
 "How much the resistance itself changes with temperature. Matching between the arms of the bridge decides how much offset drift results.", "", ["tcr"]),
("mismatch", "Bridge mismatch and offset drift", "Piezoresistive sensor", "Tiny differences between the four resistors.",
 "They produce a non-zero output at zero pressure (offset) that drifts with temperature.", "V_os = V_s·δ / 4", ["bridge resistor mismatch", "arm-to-arm tcr mismatch"]),
("johnson", "Johnson (thermal) noise", "Piezoresistive sensor", "Noise voltage of every resistor caused by heat.",
 "It is unavoidable and grows with resistance, temperature and bandwidth.", "e_j = √(4k_B T R)", []),
("one_over_f", "1/f noise corner", "Piezoresistive sensor", "Frequency below which low-frequency noise takes over.",
 "Below the corner frequency the noise per √Hz rises as 1/f. It matters most for slow DC pressure measurements.", "", ["1/f noise corner"]),
("plate_resonance", "Diaphragm resonance (f₁)", "Piezoresistive sensor", "Lowest vibration frequency of the diaphragm.",
 "The sensor should be used well below it. It falls when the diaphragm becomes thinner or wider, so it limits how much sensitivity you can gain.", "", ["diaphragm resonance f1"]),
("stiffening", "Membrane stiffening", "Piezoresistive sensor", "Large deflections make the plate stiffer.",
 "When the deflection reaches the thickness the plate stretches like a drum skin. The app includes a simplified correction and warns when it is used near its limit.", "", ["membrane-stiffening coefficient", "centre deflection / thickness"]),

# =====================================================================  PIEZOELECTRIC
("piezoelectric", "Piezoelectric effect", "Piezoelectric sensor", "Some crystals and ceramics generate charge when squeezed.",
 "The charge is proportional to the force. Because it is a charge, it leaks away, so the sensor is used for dynamic forces (vibration, impact), not for static loads.", "Q = d·F", []),
("d33", "Piezoelectric coefficient d₃₃", "Piezoelectric sensor", "Charge per newton in the direction of the force.",
 "Given in pC/N. PZT-5H has about 590 pC/N; quartz only 2.3 pC/N. A higher value gives more charge.", "", ["d33"]),
("d31", "Piezoelectric coefficient d₃₁", "Piezoelectric sensor", "Charge per newton for force applied sideways.",
 "In transverse mode a long, thin element (large L/t) gives a large amplification of the charge.", "", ["d31", "loaded length / thickness l/t"]),
("perm", "Relative permittivity (εr)", "Piezoelectric sensor", "How well the material stores electric charge.",
 "Sets the capacitance of the element: C = ε₀εᵣA/t.", "", ["relative permittivity"]),
("layers", "Stacked layers (n)", "Piezoelectric sensor", "Several thin piezo layers wired in parallel.",
 "The charge multiplies by n, and so does the capacitance.", "", ["number of stacked layers n"]),
("cp", "Sensor capacitance (C_p)", "Piezoelectric sensor", "Capacitance of the piezo element.", "Together with cable capacitance it sets the voltage sensitivity.", "", ["sensor capacitance c_p", "total capacitance c_tot"]),
("voltage_amp", "Voltage amplifier", "Piezoelectric sensor", "A read-out that measures the voltage across the element.",
 "Simple, but the sensitivity falls when the cable adds capacitance, and leakage through the input resistance sets a low-frequency limit.", "S_V = (Q/F)/(C_p + C_c)", []),
("charge_amp", "Charge amplifier", "Piezoelectric sensor", "A read-out that converts charge to voltage with a feedback capacitor.",
 "The sensitivity no longer depends on the cable, and the low-frequency limit is set by the feedback resistor and capacitor.", "S_V = (Q/F)/C_f", []),
("cable_c", "Cable capacitance (C_c)", "Piezoelectric sensor", "Capacitance of the cable and input.", "Lowers the voltage sensitivity of a voltage amplifier and raises the noise gain of a charge amplifier.", "", ["cable + input capacitance c_c", "cable capacitance c_c"]),
("time_constant", "Time constant (τ)", "Piezoelectric sensor", "How fast the charge leaks away.", "τ = R·C. A long time constant lets you measure slow forces.", "τ = R·C", ["time constant tau"]),
("f_low", "Low-frequency cut-off (f_L)", "Piezoelectric sensor", "The lowest frequency the sensor can measure.",
 "Below it the charge leaks away and the signal disappears. A charge amplifier with a large feedback resistor gives a very low cut-off.", "f_L = 1/(2πτ)", ["low-frequency cut-off f_l"]),
("mounted_resonance", "Mounted resonance", "Piezoelectric sensor", "Resonance of the sensor when fitted to a structure.", "The upper frequency limit; the response is amplified near it.", "", ["mounted resonance f_res", "resonance amplification"]),
("noise_gain", "Noise gain", "Piezoelectric sensor", "How much a charge amplifier magnifies its own voltage noise.", "It rises with the cable capacitance.", "G_n = 1 + C_tot/C_f", []),
("voltage_coeff", "Voltage coefficient (g)", "Piezoelectric sensor", "Voltage produced per unit stress; g = d/ε.", "A material with a large g (PVDF, quartz) is good for voltage-mode sensing.", "", ["voltage coefficient g"]),
("piezo_materials", "Piezoelectric materials", "Piezoelectric sensor", "PZT, quartz, PVDF, BaTiO₃, AlN, ZnO.",
 "PZT ceramics have the highest d (high sensitivity). Quartz is very stable with low drift. PVDF is a flexible polymer. AlN and ZnO can be deposited as thin films for MEMS.", "", ["piezoelectric material"]),

# =====================================================================  OPTICAL
("wgm", "Whispering-gallery mode (WGM)", "Optical sensor", "Light that circles along the inner rim of a tiny sphere, ring or disk.",
 "Total internal reflection keeps the light going round and round. The resonance is very sharp (high Q), so a very small shift caused by the analyte can be detected.", "2πR·n_eff = mλ", ["whispering-gallery mode"]),
("resonance", "Resonance", "Optical sensor", "A wavelength at which light is strongly stored in the cavity.",
 "Seen as a narrow dip in the transmitted light. The sensor measures how far the dip moves.", "", ["resonance angle (water)"]),
("q_optical", "Optical quality factor (Q)", "Optical sensor", "How narrow the resonance is: Q = λ/linewidth.",
 "Q of 10⁶ means light circulates about a million times. High Q gives narrow lines and small detection limits, but is hard to keep in water.", "Q = λ / Γ", ["loaded quality factor q"]),
("fwhm", "Linewidth (FWHM)", "Optical sensor", "Full width of the resonance dip at half its depth.",
 "The narrower it is, the more precisely the dip position can be found.", "Γ = λ/Q", ["linewidth (fwhm)", "dip width (fwhm)"]),
("fsr", "Free spectral range (FSR)", "Optical sensor", "Wavelength spacing between neighbouring resonances.", "Sets how far the dip can move before it is confused with the next one.", "FSR ≈ λ²/(2πR·n_g)", ["free spectral range"]),
("evanescent", "Evanescent field / fraction (η)", "Optical sensor", "The part of the light that reaches outside the resonator.",
 "Only this tail 'feels' the liquid. A larger fraction gives a higher sensitivity but often lowers Q. For microspheres it is estimated by a scaling law: η falls as the radius grows.", "η ≈ (λ/2πRn)^(2/3)", ["evanescent fraction eta", "evanescent fraction", "eta (manual)"]),
("n_eff", "Effective index (n_eff)", "Optical sensor", "Refractive index 'seen' by the guided light.", "Enters the resonance condition and the sensitivity S = λη/n_eff.", "", ["mode / effective index n_eff", "effective index n_eff"]),
("refractive_index", "Refractive index", "Optical sensor", "How much slower light travels in a material.", "Water is about 1.33, glass 1.45, silicon 3.48. Changes of the analyte concentration change the index of the liquid.", "", ["prism refractive index"]),
("thermo_optic", "Thermo-optic coefficient (dn/dT)", "Optical sensor", "Change of refractive index with temperature.",
 "It shifts the resonance when the temperature changes. Water has −1×10⁻⁴ per K, which competes with the signal you want.", "", ["resonator thermo-optic dn/dt", "thermo-optic (1/n)dn/dt", "thermal drift dlambda/dt"]),
("thermal_expansion", "Thermal expansion", "Optical sensor", "Growth of the resonator with temperature.", "Makes the cavity longer and moves the resonance to longer wavelengths.", "", ["thermal expansion"]),
("dip_snr", "Dip-depth-to-noise ratio", "Optical sensor", "Depth of the resonance dip divided by the noise.", "The higher it is, the more accurately the dip position can be located.", "", []),
("pts_linewidth", "Points per linewidth", "Optical sensor", "How many wavelength samples fall across the dip.", "More points give a better estimate of the dip position.", "", []),
("crlb", "Cramér-Rao bound", "Optical sensor", "The best precision any method can achieve for the dip position.",
 "The app uses it as the read-out noise of resonance sensors: σ = Γ·√(2/(πN)) / SNR. A real instrument is somewhat worse.", "", ["read-out noise sigma"]),
("fom", "Figure of merit (FoM)", "Optical sensor", "Sensitivity divided by linewidth: a fair way to compare sensors.", "High sensitivity is only useful if the line is also narrow.", "FoM = S / FWHM", ["figure of merit s / fwhm"]),
("microsphere", "Microsphere, microtoroid, microring, microbubble", "Optical sensor", "Different shapes of WGM resonator.",
 "Microspheres are simple silica beads; microtoroids are chip-based with very high Q; rings are made by lithography (Si, Si₃N₄) and are easy to integrate; microbubbles are hollow so liquid flows inside.", "", []),
("fbg", "Fibre Bragg grating (FBG)", "Optical sensor", "A periodic pattern in a fibre that reflects one wavelength.",
 "Stretching the fibre or changing its temperature shifts the reflected wavelength, so it measures strain and temperature.", "λ_B = 2·n_eff·Λ", ["fibre bragg grating"]),
("bragg", "Bragg wavelength (λ_B)", "Optical sensor", "The wavelength the grating reflects.", "About 1550 nm in telecom fibre.", "", ["bragg wavelength lambda_b", "grating period"]),
("pe", "Photo-elastic coefficient (p_e)", "Optical sensor", "How strain changes the glass's refractive index.", "About 0.22 for silica; it reduces the strain response to 1−p_e.", "", ["photo-elastic coefficient p_e"]),
("kt", "Strain-transfer efficiency", "Optical sensor", "How much of the structure's strain reaches the fibre.", "Glue or coating layers reduce it below 100 %.", "", ["strain-transfer efficiency"]),
("microstrain", "Microstrain (µε)", "Optical sensor", "Strain of one part in a million.", "1 µε = 10⁻⁶. Typical steel structures move a few hundred µε.", "", ["ue", "µε"]),
("grating_length", "Grating length and index modulation", "Optical sensor", "Set the width of the reflected peak.", "A long grating with a small index modulation has a narrow peak.", "", ["grating length l_g", "index modulation dn"]),
("efpi", "Fabry-Perot interferometer (EFPI)", "Optical sensor", "Two mirrors forming a tiny cavity; the light interferes.",
 "One mirror is the fibre end, the other a thin diaphragm that bends with pressure. The cavity length change is read from the interference fringe.", "", ["fabry-perot interferometer"]),
("cavity_length", "Cavity length (L₀)", "Optical sensor", "Distance between fibre and diaphragm.", "A long cavity reduces the fringe visibility because the light spreads out.", "", ["cavity length l0"]),
("visibility", "Fringe visibility (V)", "Optical sensor", "Contrast of the interference fringes.", "High visibility means a bigger signal for a given phase change.", "V = (I_max − I_min)/(I_max + I_min)", ["effective visibility", "intrinsic fringe visibility v0"]),
("quadrature", "Quadrature point", "Optical sensor", "The operating point of steepest slope.", "Biased half-way up a fringe, the output changes most and is most linear.", "", ["bias offset from quadrature"]),
("phase_change", "Phase change (Δφ)", "Optical sensor", "Shift of the interference phase caused by the diaphragm.", "Δφ = 4π·w/λ for a diaphragm deflection w.", "", ["phase change at full scale", "centre deflection at full scale"]),
("rin", "Laser RIN", "Optical sensor", "Relative intensity noise of the laser.", "Random power fluctuations of the laser that appear as noise on the detector.", "", ["laser rin"]),
("tia", "Transimpedance gain", "Optical sensor", "Converts the photodiode current to voltage.", "Ohms of gain; larger gain gives a larger signal but less bandwidth.", "", ["transimpedance gain", "received optical power", "mean detector voltage"]),
("sealed_cavity", "Sealed cavity error", "Optical sensor", "Trapped gas expands when heated.", "It pushes the diaphragm and looks like a pressure change: about 0.34 kPa per kelvin.", "", ["sealed-cavity thermal error"]),
("spr", "Surface plasmon resonance (SPR)", "Optical sensor", "Light excites electron waves on a thin metal film.",
 "At one angle of incidence, energy goes into the surface wave and the reflected light shows a dip. The dip angle depends strongly on the refractive index of the liquid on the film.", "", ["surface plasmon resonance"]),
("kretschmann", "Kretschmann configuration", "Optical sensor", "Prism–metal film–liquid stack used for SPR.", "Light enters through a prism, reflects from the thin gold or silver film and is detected.", "", ["metal film", "film thickness d"]),
("critical_angle", "Critical angle", "Optical sensor", "Smallest angle for total internal reflection.", "The SPR dip always lies above it.", "θ_c = asin(n_s / n_p)", ["critical angle"]),
("dip_depth", "Dip depth", "Optical sensor", "How much light is absorbed at resonance.", "A deep, narrow dip is easiest to locate.", "1 − R_min", ["dip depth"]),

# =====================================================================  MACHINE LEARNING
("ml", "Machine learning", "Machine learning", "Programs that learn patterns from data instead of being told the equations.",
 "Here it is used to predict sensor properties, suggest better designs, correct drift and find faults.", "", []),
("surrogate", "Surrogate model", "Machine learning", "A fast stand-in for a slower calculation.",
 "It learns from many simulated designs, then predicts the sensitivity of a new design instantly. It is only reliable inside the range of parameters it was trained on.", "", []),
("features", "Features (inputs)", "Machine learning", "The design parameters the model learns from.", "For example diaphragm side length, thickness and supply voltage.", "", ["input features (design parameters)"]),
("target", "Target", "Machine learning", "The number the model tries to predict.", "Usually the sensitivity, but it can be noise or detection limit.", "", ["target to predict"]),
("train_test", "Training and test data", "Machine learning", "Data to learn from, and data kept back to check the result.",
 "The model never sees the test data while learning. Its accuracy on that unseen data is an honest measure of how it will do on new designs.", "", ["test fraction", "hold-out", "hold-out windows"]),
("cv", "Cross-validation (CV)", "Machine learning", "Repeating the train/test split several times.",
 "The data is cut into k folds; each fold takes a turn as the test set. The mean CV R² and its spread show how stable the model is.", "", ["cross-validation folds", "cv r²"]),
("overfitting", "Overfitting", "Machine learning", "Memorising the training data instead of learning the pattern.", "A big gap between training and test accuracy is the warning sign.", "", []),
("mape", "MAPE", "Machine learning", "Mean absolute percentage error.", "The average size of the error as a percentage of the true value. 5 % means predictions are typically 5 % off.", "", ["mape", "test mape"]),
("test_r2", "Test R²", "Machine learning", "R² measured on unseen designs.", "1 is perfect; 0 is no better than always guessing the mean.", "", ["test r²", "r² (log scale)"]),
("log_transform", "Log-transform", "Machine learning", "Learning on logarithms instead of raw numbers.",
 "Sensitivities are products of powers of the parameters (S ∝ a²/h²). On a log scale that becomes a straight line, which is easy to learn and extrapolates more sensibly.", "ln S = ln C + Σ eᵢ·ln pᵢ", ["log-transform target", "log-transform features"]),
("ridge", "Ridge regression", "Machine learning", "A linear model with a penalty on large coefficients.", "Simple and stable. With log-transform its coefficients are the scaling exponents.", "", ["ridge (linear)"]),
("poly_ridge", "Polynomial ridge", "Machine learning", "Ridge regression that also uses squares and products of the inputs.", "Captures curvature and interactions with few data.", "", ["polynomial (degree 2) + ridge", "polynomial (deg 2) in (y, t)"]),
("rf", "Random forest", "Machine learning", "Many decision trees whose answers are averaged.", "Robust and needs little tuning, but predicts in steps and cannot extrapolate.", "", ["random forest"]),
("gb", "Gradient boosting", "Machine learning", "Trees added one after another, each fixing the last one's errors.", "Often accurate; like the forest, it cannot go beyond the range of the training data.", "", ["gradient boosting"]),
("mlp", "Neural network (MLP)", "Machine learning", "Layers of simple units that learn a smooth curve.", "Works well for smooth physics with enough data.", "", ["neural network (mlp)"]),
("perm_importance", "Permutation importance", "Machine learning", "How much accuracy drops when one input is shuffled.", "A big drop means the model depends on that input. The error bars show the spread over several shuffles.", "", ["permutation importance"]),
("exponent", "Scaling exponent", "Machine learning", "The power with which a parameter changes the sensitivity.", "Exponent +2 for the diaphragm side length means doubling it multiplies sensitivity by 4.", "S ∝ pᵉ", ["scaling exponents"]),
("whatif", "What-if curve", "Machine learning", "Prediction of the model versus the physics when one parameter changes.", "Shows where the surrogate is accurate and where it drifts away.", "", ["what-if curve: machine learning vs. physics"]),
("optimiser", "Design optimisation", "Machine learning", "Searching the parameter space for the best design.",
 "Differential evolution tries many candidate designs on the surrogate and keeps improving them. A constraint (for example bandwidth ≥ a limit) is enforced by a penalty.", "", ["find the best design"]),
("de", "Differential evolution", "Machine learning", "A population-based search that needs no derivatives.", "Good for rough landscapes with several local optima.", "", []),
("refinement", "Refinement rounds", "Machine learning", "Checking the optimum with the physics and retraining.",
 "Each round evaluates the surrogate's best design with the real model, adds designs around it to the training data and retrains. This stops the optimiser from trusting the surrogate where it extrapolates.", "", ["refinement rounds with the physics model"]),
("extrapolation", "Extrapolation", "Machine learning", "Predicting outside the range of the training data.", "Unreliable. The app warns when the optimum sits on a search bound.", "", []),
("classical_cal", "Classical calibration", "Machine learning", "A straight-line calibration made at one temperature.", "It ignores temperature, so its error grows when the sensor is hot or cold.", "", ["classical calibration error", "classical linear calibration (ignores t)"]),
("drift_correction", "Drift correction", "Machine learning", "Using temperature as an extra input to remove drift.",
 "The model learns x = g(y, T): the measurand from the output and the temperature.", "", ["best ml error", "improvement", "linear in (y, t)", "drift correction"]),
("fault_detection", "Fault detection", "Machine learning", "Recognising that a sensor is unhealthy from its signal.",
 "Windows of the residual between the measured and healthy output are summarised by features; a classifier names the fault.", "", []),
("fault_types", "Fault types", "Machine learning", "Drift, gain loss, noise increase, spikes, stuck, saturation.",
 "Drift: slow offset ramp. Gain loss: the sensitivity fades. Noise increase: more scatter. Spikes: outliers. Stuck: frozen output. Saturation: output clipped at a limit.", "", []),
("window", "Window", "Machine learning", "A short stretch of the signal analysed as one unit.", "Longer windows give steadier features but react more slowly to a fault.", "", ["window length (samples)"]),
("kurtosis", "Kurtosis and skewness", "Machine learning", "Numbers describing the shape of the noise distribution.", "High kurtosis means outliers (spikes) are present.", "", []),
("confusion", "Confusion matrix", "Machine learning", "A table of true against predicted classes.", "The diagonal shows correct answers. Off-diagonal numbers are the mix-ups.", "", ["confusion matrix (hold-out windows)"]),
("accuracy_ml", "Accuracy (classifier)", "Machine learning", "Share of windows classified correctly.", "", "", ["accuracy"]),
("f1", "Macro F1", "Machine learning", "Balanced score over all classes.", "Averages precision and recall per class, so rare faults count as much as common ones.", "", ["macro f1"]),
("iforest", "Isolation Forest", "Machine learning", "Flags anything unusual without knowing the fault type.",
 "It is trained on healthy data only and isolates points that look different. 'Faults caught / false alarms' shows how many faults it found and how often it cried wolf.", "", ["isolation forest"]),
("anomaly_share", "Expected anomaly share", "Machine learning", "Your guess of how many windows are faulty.", "The Isolation Forest flags about this share. Set it close to the real fraction.", "", ["expected anomaly share"]),
("false_alarm", "False alarm", "Machine learning", "A healthy window wrongly flagged as faulty.", "", "", []),
("noise_floor_pct", "Noise floor (% FS)", "Machine learning", "Extra measurement noise added to simulated data.", "Makes the simulated data more like a real, noisy measurement.", "", ["noise floor [% fs]"]),
("severity", "Fault severity", "Machine learning", "How strong the injected faults are.", "1.0 is the default; smaller values make the faults harder to spot.", "", ["fault severity"]),
("design_log", "Design log and raw log", "Data", "Tables of what you have collected in the Sensor Lab.", "The design log holds one row per design (parameters and figures of merit); the raw log holds every single reading. Both can be downloaded as CSV.", "", []),
("csv", "CSV file", "Data", "A plain table saved as text, values separated by commas.", "Open it in Excel. Column names starting with p_ are treated as design parameters in the ML Studio.", "", []),
]
# fmt: on
